### PR TITLE
Fix/align deptree interface

### PR DESCRIPTION
**Pull request by miiila**
- [x] Tests written and linted
- [ ] Documentation written / README.md updated [https://snyk.io/docs/snyk-for-dotnet/](i)
- [x] Follows [CONTRIBUTING agreement](CONTRIBUTING.md)
- [x] Commit history is tidy [https://git-scm.com/book/en/v2/Git-Branching-Rebasing](i)
- [x] Reviewed by Snyk team

### What this does

DepTree intreface has diverged from the one used in e.g. DepGraph.
The biggest difference is the dependencies keys, which is not mandatory anymore.
This change is a prereq for using depgraphs.

### Notes for the reviewer

Just carefully review tests and think of potential impact and omitted parts.

### More information

- [BST-631](https://snyksec.atlassian.net/browse/BST-631)

### CODE REVIEW

**Comment by lili2311** [comment]
👋 Please could you give a little more context:
- Why does removed empty dependencies object helping towards moving to a graph?
- How does Registry and other upstreams handle this change? Do they care?

**Comment by miiila** [comment]
@lili2311 

> Why does removed empty dependencies object helping towards moving to a graph?

As I say in description, `DepTree intreface has diverged from the one used in e.g. DepGraph.` The main difference is in mandatory vs optional `dependencies` property. Once moved to `graph function`, tree created out of the graph should be the same as the one created by `tree function`. Therefore the interface has to be same and that's why we need to align those.

> How does Registry and other upstreams handle this change? Do they care?

That's what we spoke about with @darscan. What needs to be put back is top level `dependencies` key which might be somewhere used to checks. Apart from that, everything should be ok.

**Comment by darscan** [comment]
> What needs to be put back is top level dependencies key which might be somewhere used to checks

Can we do that then please :D

**Comment by darscan** [comment]
I still think you need to split the type in two, like we do in the dep-graph lib: top-level tree type (with mandatory `dependencies` property) VS recursive dep type (with optional `dependencies` property)

Or, just use the dep-graph type in

**Pull request merged**
