### PR TITLE
Add properties to the lockfile (ref: #98)

### PR DESCRIPTION
**Pull request by abdulhannanali**
- [x] Tests written and linted
- [ ] Documentation written / README.md updated [https://snyk.io/docs/snyk-for-node/](i)
- [x] Follows [CONTRIBUTING agreement](CONTRIBUTING.md)
- [ ] Commit history is tidy [https://git-scm.com/book/en/v2/Git-Branching-Rebasing](i)
- [ ] Reviewed by Snyk team

### What this does

This PR mainly adds following four properties to the lockfile dependency tree that were previously ignored

- `resolved`
- `integrity`
- `checksum`
- `resolution`

It also updates the expected dependency tree fixtures accordingly and moves `yarn.test.ts` to the `jest`. The file was moved to jest since it was timing out with tap and the test comparison was taking forever to run. I pledge to move the whole test code of this repo to Jest and also add snapshotting to make it simpler for everyone to add properties in future.

_Explain why this PR exists_

This PR exists since we want this functionality for https://github.com/lirantal/lockfile-lint/issues/101 and @orsagie showed willingness for these properties to be added in the repo #98 

### Notes for the reviewer

_Instructions on how to run this locally, background context, what to review, questions…_

### More information

- [SC-XXXX]()
- [Link to documentation]()

### Screenshots

_Visuals that may help the reviewer_

### CODE REVIEW

**Comment by abdulhannanali** [comment]
@lirantal Could you take a look at this when you get a chance, so we can move https://github.com/lirantal/lockfile-lint/issues/101 forward?

**Comment by admons** [comment]
Hey @abdulhannanali , thanks for raising this PR!
We currently have some WIP branch and prioritised to do some work on this area in the next sprint (or the one after)
we'll see what's missing and might use this PR

We'll let you know when we'll get to this

**Comment by abdulhannanali** [comment]
@admons Thanks for considering. I look forward for this integration. Just curious, is it about the dependency graph? I would love to contribute in that area, if given some directions about approach, if you're accepting contributions there.

**Comment by abdulhannanali** [comment]
> @admons Thanks for considering. I look forward for this integration. Just curious, is it about the dependency graph? I would love to contribute in that area, if given some directions about approach, if you're accepting contributions there.

I see, it's related to yarn resolutions. Will be watching those PRs.

**Review by milahu — APPROVED** [review]
lgtm : )

**Comment by abdulhannanali** [comment]
@milahu Thank you very much for approving. I will take a look tomorrow to resolve the conflicts, in case you are not already working on it.

**Comment by calderonth** [comment]
Hello!
Would be keen to know the status of this PR?
It seemed like it was addressing missing features from the lockfile parsing logic.
@lirantal @admons

**Comment by calderonth** [comment]
@JamesPatrickGill , sorry to tag, would be keen on knowing what could be done for this PR to reset/progress again?

**Pull request closed without merging**
